//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("RemoteDatabaseModel", "FK_ZDST_TOWARY", "TOWARY", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PharmacyCondition.RemoteDatabase.TOWARY), "ZDST", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PharmacyCondition.RemoteDatabase.ZDST), true)]
[assembly: EdmRelationshipAttribute("RemoteDatabaseModel", "FK_KL_ZDST", "ZDST", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PharmacyCondition.RemoteDatabase.ZDST), "ZDST_KLAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PharmacyCondition.RemoteDatabase.ZDST_KLAS), true)]

#endregion

namespace PharmacyCondition.RemoteDatabase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RemoteDatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RemoteDatabaseEntities object using the connection string found in the 'RemoteDatabaseEntities' section of the application configuration file.
        /// </summary>
        public RemoteDatabaseEntities() : base("name=RemoteDatabaseEntities", "RemoteDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RemoteDatabaseEntities object.
        /// </summary>
        public RemoteDatabaseEntities(string connectionString) : base(connectionString, "RemoteDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RemoteDatabaseEntities object.
        /// </summary>
        public RemoteDatabaseEntities(EntityConnection connection) : base(connection, "RemoteDatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TOWARY> TOWARY
        {
            get
            {
                if ((_TOWARY == null))
                {
                    _TOWARY = base.CreateObjectSet<TOWARY>("TOWARY");
                }
                return _TOWARY;
            }
        }
        private ObjectSet<TOWARY> _TOWARY;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ZDST> ZDST
        {
            get
            {
                if ((_ZDST == null))
                {
                    _ZDST = base.CreateObjectSet<ZDST>("ZDST");
                }
                return _ZDST;
            }
        }
        private ObjectSet<ZDST> _ZDST;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ZDST_KLAS> ZDST_KLAS
        {
            get
            {
                if ((_ZDST_KLAS == null))
                {
                    _ZDST_KLAS = base.CreateObjectSet<ZDST_KLAS>("ZDST_KLAS");
                }
                return _ZDST_KLAS;
            }
        }
        private ObjectSet<ZDST_KLAS> _ZDST_KLAS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TOWARY EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTOWARY(TOWARY tOWARY)
        {
            base.AddObject("TOWARY", tOWARY);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ZDST EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZDST(ZDST zDST)
        {
            base.AddObject("ZDST", zDST);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ZDST_KLAS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToZDST_KLAS(ZDST_KLAS zDST_KLAS)
        {
            base.AddObject("ZDST_KLAS", zDST_KLAS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RemoteDatabaseModel", Name="TOWARY")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TOWARY : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TOWARY object.
        /// </summary>
        /// <param name="iD_APTEKI">Initial value of the ID_APTEKI property.</param>
        /// <param name="iD_TOWARY">Initial value of the ID_TOWARY property.</param>
        /// <param name="nAZWA">Initial value of the NAZWA property.</param>
        public static TOWARY CreateTOWARY(global::System.Int32 iD_APTEKI, global::System.Int32 iD_TOWARY, global::System.String nAZWA)
        {
            TOWARY tOWARY = new TOWARY();
            tOWARY.ID_APTEKI = iD_APTEKI;
            tOWARY.ID_TOWARY = iD_TOWARY;
            tOWARY.NAZWA = nAZWA;
            return tOWARY;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_APTEKI
        {
            get
            {
                return _ID_APTEKI;
            }
            set
            {
                if (_ID_APTEKI != value)
                {
                    OnID_APTEKIChanging(value);
                    ReportPropertyChanging("ID_APTEKI");
                    _ID_APTEKI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_APTEKI");
                    OnID_APTEKIChanged();
                }
            }
        }
        private global::System.Int32 _ID_APTEKI;
        partial void OnID_APTEKIChanging(global::System.Int32 value);
        partial void OnID_APTEKIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_TOWARY
        {
            get
            {
                return _ID_TOWARY;
            }
            set
            {
                if (_ID_TOWARY != value)
                {
                    OnID_TOWARYChanging(value);
                    ReportPropertyChanging("ID_TOWARY");
                    _ID_TOWARY = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_TOWARY");
                    OnID_TOWARYChanged();
                }
            }
        }
        private global::System.Int32 _ID_TOWARY;
        partial void OnID_TOWARYChanging(global::System.Int32 value);
        partial void OnID_TOWARYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAZWA
        {
            get
            {
                return _NAZWA;
            }
            set
            {
                OnNAZWAChanging(value);
                ReportPropertyChanging("NAZWA");
                _NAZWA = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAZWA");
                OnNAZWAChanged();
            }
        }
        private global::System.String _NAZWA;
        partial void OnNAZWAChanging(global::System.String value);
        partial void OnNAZWAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IFUPDDATE
        {
            get
            {
                return _IFUPDDATE;
            }
            set
            {
                OnIFUPDDATEChanging(value);
                ReportPropertyChanging("IFUPDDATE");
                _IFUPDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IFUPDDATE");
                OnIFUPDDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _IFUPDDATE;
        partial void OnIFUPDDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnIFUPDDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IFUPDUSER
        {
            get
            {
                return _IFUPDUSER;
            }
            set
            {
                OnIFUPDUSERChanging(value);
                ReportPropertyChanging("IFUPDUSER");
                _IFUPDUSER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IFUPDUSER");
                OnIFUPDUSERChanged();
            }
        }
        private global::System.String _IFUPDUSER;
        partial void OnIFUPDUSERChanging(global::System.String value);
        partial void OnIFUPDUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String POSTAC
        {
            get
            {
                return _POSTAC;
            }
            set
            {
                OnPOSTACChanging(value);
                ReportPropertyChanging("POSTAC");
                _POSTAC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("POSTAC");
                OnPOSTACChanged();
            }
        }
        private global::System.String _POSTAC;
        partial void OnPOSTACChanging(global::System.String value);
        partial void OnPOSTACChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DAWKA
        {
            get
            {
                return _DAWKA;
            }
            set
            {
                OnDAWKAChanging(value);
                ReportPropertyChanging("DAWKA");
                _DAWKA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DAWKA");
                OnDAWKAChanged();
            }
        }
        private global::System.String _DAWKA;
        partial void OnDAWKAChanging(global::System.String value);
        partial void OnDAWKAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EAN_REF
        {
            get
            {
                return _EAN_REF;
            }
            set
            {
                OnEAN_REFChanging(value);
                ReportPropertyChanging("EAN_REF");
                _EAN_REF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EAN_REF");
                OnEAN_REFChanged();
            }
        }
        private global::System.String _EAN_REF;
        partial void OnEAN_REFChanging(global::System.String value);
        partial void OnEAN_REFChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RemoteDatabaseModel", "FK_ZDST_TOWARY", "ZDST")]
        public EntityCollection<ZDST> ZDST
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ZDST>("RemoteDatabaseModel.FK_ZDST_TOWARY", "ZDST");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ZDST>("RemoteDatabaseModel.FK_ZDST_TOWARY", "ZDST", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RemoteDatabaseModel", Name="ZDST")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ZDST : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ZDST object.
        /// </summary>
        /// <param name="iD_APTEKI">Initial value of the ID_APTEKI property.</param>
        /// <param name="iD_ZDST">Initial value of the ID_ZDST property.</param>
        /// <param name="iD_DOSTAWY">Initial value of the ID_DOSTAWY property.</param>
        /// <param name="pOZYCJA">Initial value of the POZYCJA property.</param>
        /// <param name="dATA">Initial value of the DATA property.</param>
        /// <param name="iD_TOWARY">Initial value of the ID_TOWARY property.</param>
        /// <param name="sZTUK">Initial value of the SZTUK property.</param>
        /// <param name="sZTUK_JP">Initial value of the SZTUK_JP property.</param>
        /// <param name="sTAN">Initial value of the STAN property.</param>
        /// <param name="jEDNOSTKA">Initial value of the JEDNOSTKA property.</param>
        public static ZDST CreateZDST(global::System.Int32 iD_APTEKI, global::System.Double iD_ZDST, global::System.Int32 iD_DOSTAWY, global::System.Int32 pOZYCJA, global::System.DateTime dATA, global::System.Int32 iD_TOWARY, global::System.Double sZTUK, global::System.Double sZTUK_JP, global::System.Double sTAN, global::System.Int32 jEDNOSTKA)
        {
            ZDST zDST = new ZDST();
            zDST.ID_APTEKI = iD_APTEKI;
            zDST.ID_ZDST = iD_ZDST;
            zDST.ID_DOSTAWY = iD_DOSTAWY;
            zDST.POZYCJA = pOZYCJA;
            zDST.DATA = dATA;
            zDST.ID_TOWARY = iD_TOWARY;
            zDST.SZTUK = sZTUK;
            zDST.SZTUK_JP = sZTUK_JP;
            zDST.STAN = sTAN;
            zDST.JEDNOSTKA = jEDNOSTKA;
            return zDST;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_APTEKI
        {
            get
            {
                return _ID_APTEKI;
            }
            set
            {
                if (_ID_APTEKI != value)
                {
                    OnID_APTEKIChanging(value);
                    ReportPropertyChanging("ID_APTEKI");
                    _ID_APTEKI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_APTEKI");
                    OnID_APTEKIChanged();
                }
            }
        }
        private global::System.Int32 _ID_APTEKI;
        partial void OnID_APTEKIChanging(global::System.Int32 value);
        partial void OnID_APTEKIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ID_ZDST
        {
            get
            {
                return _ID_ZDST;
            }
            set
            {
                if (_ID_ZDST != value)
                {
                    OnID_ZDSTChanging(value);
                    ReportPropertyChanging("ID_ZDST");
                    _ID_ZDST = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_ZDST");
                    OnID_ZDSTChanged();
                }
            }
        }
        private global::System.Double _ID_ZDST;
        partial void OnID_ZDSTChanging(global::System.Double value);
        partial void OnID_ZDSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_DOSTAWY
        {
            get
            {
                return _ID_DOSTAWY;
            }
            set
            {
                OnID_DOSTAWYChanging(value);
                ReportPropertyChanging("ID_DOSTAWY");
                _ID_DOSTAWY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_DOSTAWY");
                OnID_DOSTAWYChanged();
            }
        }
        private global::System.Int32 _ID_DOSTAWY;
        partial void OnID_DOSTAWYChanging(global::System.Int32 value);
        partial void OnID_DOSTAWYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 POZYCJA
        {
            get
            {
                return _POZYCJA;
            }
            set
            {
                OnPOZYCJAChanging(value);
                ReportPropertyChanging("POZYCJA");
                _POZYCJA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("POZYCJA");
                OnPOZYCJAChanged();
            }
        }
        private global::System.Int32 _POZYCJA;
        partial void OnPOZYCJAChanging(global::System.Int32 value);
        partial void OnPOZYCJAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATA
        {
            get
            {
                return _DATA;
            }
            set
            {
                OnDATAChanging(value);
                ReportPropertyChanging("DATA");
                _DATA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATA");
                OnDATAChanged();
            }
        }
        private global::System.DateTime _DATA;
        partial void OnDATAChanging(global::System.DateTime value);
        partial void OnDATAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_TOWARY
        {
            get
            {
                return _ID_TOWARY;
            }
            set
            {
                OnID_TOWARYChanging(value);
                ReportPropertyChanging("ID_TOWARY");
                _ID_TOWARY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ID_TOWARY");
                OnID_TOWARYChanged();
            }
        }
        private global::System.Int32 _ID_TOWARY;
        partial void OnID_TOWARYChanging(global::System.Int32 value);
        partial void OnID_TOWARYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SZTUK
        {
            get
            {
                return _SZTUK;
            }
            set
            {
                OnSZTUKChanging(value);
                ReportPropertyChanging("SZTUK");
                _SZTUK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SZTUK");
                OnSZTUKChanged();
            }
        }
        private global::System.Double _SZTUK;
        partial void OnSZTUKChanging(global::System.Double value);
        partial void OnSZTUKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double SZTUK_JP
        {
            get
            {
                return _SZTUK_JP;
            }
            set
            {
                OnSZTUK_JPChanging(value);
                ReportPropertyChanging("SZTUK_JP");
                _SZTUK_JP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SZTUK_JP");
                OnSZTUK_JPChanged();
            }
        }
        private global::System.Double _SZTUK_JP;
        partial void OnSZTUK_JPChanging(global::System.Double value);
        partial void OnSZTUK_JPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double STAN
        {
            get
            {
                return _STAN;
            }
            set
            {
                OnSTANChanging(value);
                ReportPropertyChanging("STAN");
                _STAN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STAN");
                OnSTANChanged();
            }
        }
        private global::System.Double _STAN;
        partial void OnSTANChanging(global::System.Double value);
        partial void OnSTANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IFUPDDATE
        {
            get
            {
                return _IFUPDDATE;
            }
            set
            {
                OnIFUPDDATEChanging(value);
                ReportPropertyChanging("IFUPDDATE");
                _IFUPDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IFUPDDATE");
                OnIFUPDDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _IFUPDDATE;
        partial void OnIFUPDDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnIFUPDDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IFUPDUSER
        {
            get
            {
                return _IFUPDUSER;
            }
            set
            {
                OnIFUPDUSERChanging(value);
                ReportPropertyChanging("IFUPDUSER");
                _IFUPDUSER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IFUPDUSER");
                OnIFUPDUSERChanged();
            }
        }
        private global::System.String _IFUPDUSER;
        partial void OnIFUPDUSERChanging(global::System.String value);
        partial void OnIFUPDUSERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> KOREKTA_DO
        {
            get
            {
                return _KOREKTA_DO;
            }
            set
            {
                OnKOREKTA_DOChanging(value);
                ReportPropertyChanging("KOREKTA_DO");
                _KOREKTA_DO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KOREKTA_DO");
                OnKOREKTA_DOChanged();
            }
        }
        private Nullable<global::System.Double> _KOREKTA_DO;
        partial void OnKOREKTA_DOChanging(Nullable<global::System.Double> value);
        partial void OnKOREKTA_DOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BLOKADA
        {
            get
            {
                return _BLOKADA;
            }
            set
            {
                OnBLOKADAChanging(value);
                ReportPropertyChanging("BLOKADA");
                _BLOKADA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BLOKADA");
                OnBLOKADAChanged();
            }
        }
        private global::System.String _BLOKADA;
        partial void OnBLOKADAChanging(global::System.String value);
        partial void OnBLOKADAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CZYNNY
        {
            get
            {
                return _CZYNNY;
            }
            set
            {
                OnCZYNNYChanging(value);
                ReportPropertyChanging("CZYNNY");
                _CZYNNY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CZYNNY");
                OnCZYNNYChanged();
            }
        }
        private global::System.String _CZYNNY;
        partial void OnCZYNNYChanging(global::System.String value);
        partial void OnCZYNNYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> STAN0
        {
            get
            {
                return _STAN0;
            }
            set
            {
                OnSTAN0Changing(value);
                ReportPropertyChanging("STAN0");
                _STAN0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STAN0");
                OnSTAN0Changed();
            }
        }
        private Nullable<global::System.Double> _STAN0;
        partial void OnSTAN0Changing(Nullable<global::System.Double> value);
        partial void OnSTAN0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FAKT0
        {
            get
            {
                return _FAKT0;
            }
            set
            {
                OnFAKT0Changing(value);
                ReportPropertyChanging("FAKT0");
                _FAKT0 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FAKT0");
                OnFAKT0Changed();
            }
        }
        private global::System.String _FAKT0;
        partial void OnFAKT0Changing(global::System.String value);
        partial void OnFAKT0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DZAK0
        {
            get
            {
                return _DZAK0;
            }
            set
            {
                OnDZAK0Changing(value);
                ReportPropertyChanging("DZAK0");
                _DZAK0 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DZAK0");
                OnDZAK0Changed();
            }
        }
        private Nullable<global::System.DateTime> _DZAK0;
        partial void OnDZAK0Changing(Nullable<global::System.DateTime> value);
        partial void OnDZAK0Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JEDNOSTKA
        {
            get
            {
                return _JEDNOSTKA;
            }
            set
            {
                OnJEDNOSTKAChanging(value);
                ReportPropertyChanging("JEDNOSTKA");
                _JEDNOSTKA = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JEDNOSTKA");
                OnJEDNOSTKAChanged();
            }
        }
        private global::System.Int32 _JEDNOSTKA;
        partial void OnJEDNOSTKAChanging(global::System.Int32 value);
        partial void OnJEDNOSTKAChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RemoteDatabaseModel", "FK_ZDST_TOWARY", "TOWARY")]
        public TOWARY TOWARY
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TOWARY>("RemoteDatabaseModel.FK_ZDST_TOWARY", "TOWARY").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TOWARY>("RemoteDatabaseModel.FK_ZDST_TOWARY", "TOWARY").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TOWARY> TOWARYReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TOWARY>("RemoteDatabaseModel.FK_ZDST_TOWARY", "TOWARY");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TOWARY>("RemoteDatabaseModel.FK_ZDST_TOWARY", "TOWARY", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RemoteDatabaseModel", "FK_KL_ZDST", "ZDST_KLAS")]
        public EntityCollection<ZDST_KLAS> ZDST_KLAS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ZDST_KLAS>("RemoteDatabaseModel.FK_KL_ZDST", "ZDST_KLAS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ZDST_KLAS>("RemoteDatabaseModel.FK_KL_ZDST", "ZDST_KLAS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="RemoteDatabaseModel", Name="ZDST_KLAS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ZDST_KLAS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ZDST_KLAS object.
        /// </summary>
        /// <param name="iD_APTEKI">Initial value of the ID_APTEKI property.</param>
        /// <param name="iD_ZDST">Initial value of the ID_ZDST property.</param>
        /// <param name="iD_KLASYFIKACJE">Initial value of the ID_KLASYFIKACJE property.</param>
        /// <param name="wARTOSC">Initial value of the WARTOSC property.</param>
        public static ZDST_KLAS CreateZDST_KLAS(global::System.Int32 iD_APTEKI, global::System.Double iD_ZDST, global::System.Int32 iD_KLASYFIKACJE, global::System.String wARTOSC)
        {
            ZDST_KLAS zDST_KLAS = new ZDST_KLAS();
            zDST_KLAS.ID_APTEKI = iD_APTEKI;
            zDST_KLAS.ID_ZDST = iD_ZDST;
            zDST_KLAS.ID_KLASYFIKACJE = iD_KLASYFIKACJE;
            zDST_KLAS.WARTOSC = wARTOSC;
            return zDST_KLAS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_APTEKI
        {
            get
            {
                return _ID_APTEKI;
            }
            set
            {
                if (_ID_APTEKI != value)
                {
                    OnID_APTEKIChanging(value);
                    ReportPropertyChanging("ID_APTEKI");
                    _ID_APTEKI = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_APTEKI");
                    OnID_APTEKIChanged();
                }
            }
        }
        private global::System.Int32 _ID_APTEKI;
        partial void OnID_APTEKIChanging(global::System.Int32 value);
        partial void OnID_APTEKIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double ID_ZDST
        {
            get
            {
                return _ID_ZDST;
            }
            set
            {
                if (_ID_ZDST != value)
                {
                    OnID_ZDSTChanging(value);
                    ReportPropertyChanging("ID_ZDST");
                    _ID_ZDST = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_ZDST");
                    OnID_ZDSTChanged();
                }
            }
        }
        private global::System.Double _ID_ZDST;
        partial void OnID_ZDSTChanging(global::System.Double value);
        partial void OnID_ZDSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_KLASYFIKACJE
        {
            get
            {
                return _ID_KLASYFIKACJE;
            }
            set
            {
                if (_ID_KLASYFIKACJE != value)
                {
                    OnID_KLASYFIKACJEChanging(value);
                    ReportPropertyChanging("ID_KLASYFIKACJE");
                    _ID_KLASYFIKACJE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_KLASYFIKACJE");
                    OnID_KLASYFIKACJEChanged();
                }
            }
        }
        private global::System.Int32 _ID_KLASYFIKACJE;
        partial void OnID_KLASYFIKACJEChanging(global::System.Int32 value);
        partial void OnID_KLASYFIKACJEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WARTOSC
        {
            get
            {
                return _WARTOSC;
            }
            set
            {
                if (_WARTOSC != value)
                {
                    OnWARTOSCChanging(value);
                    ReportPropertyChanging("WARTOSC");
                    _WARTOSC = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("WARTOSC");
                    OnWARTOSCChanged();
                }
            }
        }
        private global::System.String _WARTOSC;
        partial void OnWARTOSCChanging(global::System.String value);
        partial void OnWARTOSCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IFUPDDATE
        {
            get
            {
                return _IFUPDDATE;
            }
            set
            {
                OnIFUPDDATEChanging(value);
                ReportPropertyChanging("IFUPDDATE");
                _IFUPDDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IFUPDDATE");
                OnIFUPDDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _IFUPDDATE;
        partial void OnIFUPDDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnIFUPDDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IFUPDUSER
        {
            get
            {
                return _IFUPDUSER;
            }
            set
            {
                OnIFUPDUSERChanging(value);
                ReportPropertyChanging("IFUPDUSER");
                _IFUPDUSER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IFUPDUSER");
                OnIFUPDUSERChanged();
            }
        }
        private global::System.String _IFUPDUSER;
        partial void OnIFUPDUSERChanging(global::System.String value);
        partial void OnIFUPDUSERChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("RemoteDatabaseModel", "FK_KL_ZDST", "ZDST")]
        public ZDST ZDST
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ZDST>("RemoteDatabaseModel.FK_KL_ZDST", "ZDST").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ZDST>("RemoteDatabaseModel.FK_KL_ZDST", "ZDST").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ZDST> ZDSTReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ZDST>("RemoteDatabaseModel.FK_KL_ZDST", "ZDST");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ZDST>("RemoteDatabaseModel.FK_KL_ZDST", "ZDST", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
